---
title: "Dissertation code"
author: "Louise Litrico S1814797"
date: "4/1/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Moisture analysis

ANCOVA carried out to test the effect of time, soil type and irrigation level on the volumetric water content of the soil throughout the experiment. 

```r 
# ANCOVA
# Assumptions with chi-squared test and Levene's test
explanatory_table = table(moisture$day, moisture$soil_type)
print(explanatory_table)
print(chisq.test(explanatory_table))
# p-value > 0.05 so covariates are independent 
leveneTest(mean_moisture ~ irrigation_level, data = moisture)
# p-value > 0.05 so variance is equal 
# then actually fitting the model
ancova_model <- aov(mean_moisture ~ irrigation_level + soil_type + day, data = moisture)
Anova(ancova_model, type="III") 
# posthoc test 
postHocs <- glht(ancova_model, linfct = mcp(soil_type = "Tukey"))
summary(postHocs)
postHocs1 <- glht(ancova_model, linfct = mcp(irrigation_level = "Tukey"))
summary(postHocs1)
```

## Root and shoot analyses

Linear model carried out to test the effect of species, soil type and irrigation level on the root : shoot ratio values while controlling for total biomass of the individuals. 

```r
ratio1 <- ratio %>% filter(!count %in% c(67,90))  # taking out outliers
ratio_model <- lm(root_shoot ~ irrigation_level*species + soil + Dry_weight_total, data = ratio1)
summary(ratio_model)
plot(ratio_model)
summary(gvlma(ratio_model))
```

Linear model carried out to test the effect of dry shoot weight, irrigation level, soil type and species, on the dry root weight of the plants. 

```r
ratio2 <- ratio %>% filter(!count %in% c(50,67,87,90))  # taking out outliers
ratio_model1 <- lm(log(Dry_weight_root) ~ log(Dry_weight_shoot) + irrigation_level + soil + species, data = ratio2)
summary(ratio_model1)
plot(ratio_model1)
summary(gvlma(ratio_model1))
```

## Leaf area analysis

Linear model carried out to test the effect of species, soil type and irrigation level on the leaf area values while controlling for total biomass of the individuals. 

```r 
ratio3 <- ratio %>% filter(!count %in% c(38,84,92))  # taking out outliers
leaf_area_model <- lm(Leaf_area ~ species + soil + irrigation_level + Dry_weight_total, data = ratio3)
summary(leaf_area_model)
plot(leaf_area_model)
summary(gvlma(leaf_area_model))
```

## Total biomass analysis

Linear model carried out to test the effect of species, soil type and irrigation level on the total biomass of the individuals. 

```r
total_biomass_model <- lm(Dry_weight_total ~ irrigation_level*soil + species, data = ratio)
summary(total_biomass_model)
plot(total_biomass_model)
summary(gvlma(total_biomass_model))
```
